_target_: demo_generation.demogen.DemoGen

data_root: data
source_name: Assembly_2

task_n_object: 2

use_linear_interpolation: false
interpolate_step_size: 0.01

use_manual_parsing_frames: true
parsing_frames:
  motion-1: 0
  skill-1: 15
  motion-2: 25
  skill-2: 35

mask_names:
  object: obj1
  target: obj2

trans_range:
  src:
    object: [[0, 0, 0], [0, 0, 0]]
    target: [[0, 0, 0], [0, 0, 0]]
  test:
    object: [[-0.15, -0.05, 0], [0.15, 0.05, 0]]
    target: [[-0.15, -0.05, 0], [0.15, 0.05, 0]]

generation:
  range_name: test
  n_gen_per_source: 16
  render_video: True
  mode: grid
